---
#Dev: Lokesh Kamalay
##Desc: To create or delete user in target
##Usage: 
#
##To create an user:
##ansible-playbook user.yml --extra-vars "userid=123456 username=LokeshKamalay task=create"
##
##To delete an user:
##ansible-playbook -i user.yml --extra-vars "userid=123456 username=LokeshKamalay task=delete"
- name: Creates and/or Deletes Local User Account
  hosts: all
  become: True
  gather_facts: false

  tasks:
    - name: Generating Hashpassword for {{userid}}
      command: python -c 'import crypt; print crypt.crypt("{{ userid }}","Loki")' #Generating the password as the same user id.  This works only if the userid is in number
      delegate_to: localhost
      register: password
      when: task is match("create")
   
    - name: Creating user {{userid}}
      user:
         name: "{{userid}}"
         comment: "{{ username }}"
         password: "{{ password.stdout }}"
         update_password: on_create
      register: useroutput
      when: task is match("create")
    
    - name: Enforcing password reset
      shell: chage -d 0 {{ userid }}
      when: useroutput.changed

    - name: Grant Sudo Privileges
      shell: echo "{{ userid }}        ALL=(ALL)       NOPASSWD{{ ':' }} ALL" > /etc/sudoers.d/{{ username }}
      when: task is match("create")

    - name: Deleting user {{userid}}
      user:
         name: "{{userid}}"
         state: absent
         remove: yes
         force: yes
      when: task is match("delete")
