apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-index
data:
  index.html: |
    <html>
    <body>
    <h1>This is Kubernetes</h1>
    <img src="https://softwareengineeringdaily.com/wp-content/uploads/2018/07/kubernetes-logo-e1519045922814.png">
    </body>
    </html>
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysite
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: mysite
    spec:
      containers:
      - name: tomcat
        image: "httpd"
        ports:
          - containerPort: 80
        volumeMounts:
        - name: indexdata
          mountPath: /usr/local/apache2/htdocs
      volumes:
      - name: indexdata
        configMap:
          name: demo-index
---
apiVersion: v1
kind: Service
metadata: 
  name: mysite
spec: 
  type: NodePort
  selector: 
    app: mysite
  ports: 
  - name: http
    nodePort: 30023
    port: 80
    protocol: TCP
#kubectl scale deployments mysite --replicas=4
#kubectl set image deployments mysite tomcat=nginx --record
#kubectl rollout status deployments mysite
#kubectl rollout history deployment mysite
#kubectl get replicasets (rs)
#kubectl rollout undo deployment mysite
#kubectl rollout history deployment mysite --revision=3
#kubectl autoscale deployments mysite  --min=5 --max=15 --cpu-percent=8
